name: validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List format
        run: python3 scripts/validate.py transport
      - name: Shellcheck
        run: shellcheck sync-discard-list.sh
